
services:
  backend:
    image: divyanshujha/contest-backend:latest
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
      REDIS_URL: ${REDIS_URL}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    container_name: contest_backend
    ports:
      - "5000:5000"

  frontend:
    image: divyanshujha/contest-frontend:latest
    container_name: contest_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend